Upgrade select to SDK v2
ahmarsuhail/hadoop pull request #14
Opened 2022-11-08 08:33 UTC by passaro

Rebase + rework of the changes in https://github.com/ahmarsuhail/hadoop/pull/12

A few issues remain open:

Configuration - Since Select is only available on the Async client, we have to instantiate a second client, which leads to some code duplication. Also we need to investigate NTLM support.

SelectInputStream - v1 implementation could simply wrap the getRecordsInputStream() result. In v2, instead, we have to consume an asynchronous event stream and expose it as an input stream. The current implementation may need further work.

2022-11-09 09:28 UTC, ahmarsuhail requested changes
Looks good :) I just have some minor javadoc comments mostly. Will also be good to add some documentation somewhere explaining these changes and things we have concerns about. Will also think about who can review these changes better.

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +  public S3AsyncClient createS3AsyncClient(
I'm not sure if we can do anything about duplication, but it might be worth mentioning in comments why we have two clients. and also if there are any key differences b/w what's happening here and in createS3ClientV2

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/AWSClientConfig.java
> +   * Configures the proxy.
update to mention it configures proxy for the async client

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java
> +        SelectObjectContentResponseHandler th) {
consider updating variable name for `th`

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/WriteOperationHelper.java
> +   * {@inheritDoc}
curious why we need this? my understanding was that you use @inheritDoc to extend superclass documentation. but you if you don't need to add any other documentation, javadocs should get picked up automatically.

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/BlockingEnumeration.java
> +public final class BlockingEnumeration<T> implements Enumeration<T> {
misssing javdocs

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/BlockingEnumeration.java
> +package org.apache.hadoop.fs.s3a.select;
will need to add license agreement to any new classes, otherwise yetus complains

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/SelectObjectContentHelper.java
> +        SdkPublisher<SelectObjectContentEventStream>>> future =
maybe consider renaming `future` and `operationFuture`, personally found it a little difficult to differentiate what they represent

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/SelectEventStreamPublisher.java
> +import java.io.ByteArrayInputStream;
lots of unused imports here. + add license & javadocs

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/SelectInputStream.java
> +      final SelectEventStreamPublisher selectPublisher) throws IOException {
will need to update javadoc for this method

2022-11-09 09:28 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/SelectInputStream.java
>  import java.io.IOException;
there are some unused imports here

2022-11-09 16:27 UTC, passaro commented
@ahmarsuhail, I should have covered all comments. Let's sync up tomorrow.

If you can, have also a look at my refactor attempt here (separate, draft PR to avoid polluting this review): https://github.com/passaro/hadoop/pull/5.

2022-11-09 16:32 UTC, passaro commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +  public S3AsyncClient createS3AsyncClient(
I've managed to refactor most of this. Now it should be clear that the only difference is the http client builder (and proxy).

2022-11-10 08:18 UTC, ahmarsuhail requested changes
looks good, just a few minor comments.

2022-11-10 08:18 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +            .proxyConfiguration(AWSClientConfig.createProxyConfiguration(conf, bucket)))
nit: extra space

2022-11-10 08:18 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +  public S3AsyncClient createS3AsyncClient(
so much cleaner, thanks :)

2022-11-10 08:18 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +            .proxyConfiguration(AWSClientConfig.createAsyncProxyConfiguration(conf, bucket)))
nit: extra space

2022-11-10 08:18 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +        .serviceConfiguration(S3Configuration.builder()
would prefer to create this builder separately as before, feel like it's easier to make changes to this configuration that way

2022-11-10 08:18 UTC, ahmarsuhail commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/select/SelectEventStreamPublisher.java
> +}
will need to add a new line here

2022-11-10 08:31 UTC, passaro commented on hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/DefaultS3ClientFactory.java
> +            .proxyConfiguration(AWSClientConfig.createProxyConfiguration(conf, bucket)))
Where? Do you mean the indentation? It seems "correct" to me.

2022-11-10 10:12 UTC, ahmarsuhail approved these changes
+1

2022-11-10 10:20 UTC, merged